/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GYM_Project;
/**
 *
 * @author Mohamed
 */
import java.util.*;
import  java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.sun.jdi.connect.spi.Connection;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.time.LocalDateTime;  
import java.time.format.DateTimeFormatter;  
public class Member_page extends javax.swing.JFrame {
    
            Stack<Integer>stk = new Stack<>();
            
            int value_back;
                     java.sql.Connection c;
                      java.sql.Connection getdata;

                      PreparedStatement p;
                      PreparedStatement p1;

            
          Boolean flag_list = true;
                    Boolean flag_delet = true;

                
               
           
             

   
    
    /**
     * Creates new form Member_page
     */
    public Member_page() {
        initComponents();
        stk.push(0);
        //ShowData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Back_Member_page_btn = new javax.swing.JButton();
        Add_Member_page_btn = new javax.swing.JButton();
        Search_Member_page_btn = new javax.swing.JButton();
        Delet_Member_page_btn = new javax.swing.JButton();
        Update_Member_page_btn = new javax.swing.JButton();
        List_Member_page_btn = new javax.swing.JButton();
        Report_Member_page_btn = new javax.swing.JButton();
        logout_member_admin = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Search_Member_page_panel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        Search_btn = new javax.swing.JButton();
        id_search_field = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Search_Table = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        List_Member_page_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_List = new javax.swing.JTable();
        Refresh_DB = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Update_Member_page_panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Update_id_search = new javax.swing.JTextField();
        Update_pass_new = new javax.swing.JTextField();
        Update_sun_end_date_new = new javax.swing.JTextField();
        Update_coach_id_new = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Update_new_update = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        Report_Member_page_panel = new javax.swing.JPanel();
        send_report = new javax.swing.JButton();
        member_id_report_reciever = new javax.swing.JTextField();
        admin_id_report_sender = new javax.swing.JTextField();
        report_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Add_Member_page_panel = new javax.swing.JPanel();
        Member_FirstName_Add = new javax.swing.JTextField();
        Member_LastName_Add = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Submit_Add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Member_id_add = new javax.swing.JTextField();
        Member_Email_Add = new javax.swing.JTextField();
        Member_pass_add = new javax.swing.JTextField();
        Member_membership_add = new javax.swing.JTextField();
        Member_coachid_add = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Member_age_add = new javax.swing.JTextField();
        Member_sub_start = new javax.swing.JTextField();
        Member_sub_end = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Delete_Member_page_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        delet_member = new javax.swing.JButton();
        member_id_delet = new javax.swing.JTextField();
        Refresh_Delet_member = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table_List1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(62, 114, 236));
        jPanel1.setMaximumSize(new java.awt.Dimension(170, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(170, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 600));

        Back_Member_page_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back_Member_page_btn.setForeground(new java.awt.Color(62, 114, 236));
        Back_Member_page_btn.setText("Back");
        Back_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_Member_page_btnActionPerformed(evt);
            }
        });

        Add_Member_page_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Add_Member_page_btn.setForeground(new java.awt.Color(62, 114, 236));
        Add_Member_page_btn.setText("Add");
        Add_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Member_page_btnActionPerformed(evt);
            }
        });

        Search_Member_page_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search_Member_page_btn.setForeground(new java.awt.Color(62, 114, 236));
        Search_Member_page_btn.setText("Search");
        Search_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Member_page_btnActionPerformed(evt);
            }
        });

        Delet_Member_page_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delet_Member_page_btn.setForeground(new java.awt.Color(62, 114, 236));
        Delet_Member_page_btn.setText("Delete");
        Delet_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delet_Member_page_btnActionPerformed(evt);
            }
        });

        Update_Member_page_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update_Member_page_btn.setForeground(new java.awt.Color(62, 114, 236));
        Update_Member_page_btn.setText("Update");
        Update_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Member_page_btnActionPerformed(evt);
            }
        });

        List_Member_page_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        List_Member_page_btn.setForeground(new java.awt.Color(62, 114, 236));
        List_Member_page_btn.setText("List");
        List_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                List_Member_page_btnActionPerformed(evt);
            }
        });

        Report_Member_page_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Report_Member_page_btn.setForeground(new java.awt.Color(62, 114, 236));
        Report_Member_page_btn.setText("Report");
        Report_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Report_Member_page_btnActionPerformed(evt);
            }
        });

        logout_member_admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout_member_admin.setForeground(new java.awt.Color(62, 114, 236));
        logout_member_admin.setText("Log out");
        logout_member_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_member_adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(Back_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout_member_admin)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Update_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delet_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(List_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Report_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Add_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Search_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(List_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Update_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Delet_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Report_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout_member_admin)
                    .addComponent(Back_Member_page_btn))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        Search_Member_page_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Wanted Member ID :");

        Search_btn.setBackground(new java.awt.Color(62, 114, 236));
        Search_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Search_btn.setForeground(new java.awt.Color(255, 255, 255));
        Search_btn.setText("Search");
        Search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btnActionPerformed(evt);
            }
        });

        Search_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Second Name", "ID", "Sub_End_Date", "Coach Id"
            }
        ));
        jScrollPane4.setViewportView(Search_Table);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(62, 114, 236));
        jLabel23.setText("Search for a Member :");

        jLabel24.setForeground(new java.awt.Color(62, 114, 236));
        jLabel24.setText("____________________________________________________________________________");

        javax.swing.GroupLayout Search_Member_page_panelLayout = new javax.swing.GroupLayout(Search_Member_page_panel);
        Search_Member_page_panel.setLayout(Search_Member_page_panelLayout);
        Search_Member_page_panelLayout.setHorizontalGroup(
            Search_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Search_Member_page_panelLayout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addGroup(Search_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Search_Member_page_panelLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(id_search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(Search_Member_page_panelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(Search_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Search_Member_page_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
        );
        Search_Member_page_panelLayout.setVerticalGroup(
            Search_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Search_Member_page_panelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(Search_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(id_search_field, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(Search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        jTabbedPane1.addTab("tab2", Search_Member_page_panel);

        List_Member_page_panel.setBackground(new java.awt.Color(255, 255, 255));

        Table_List.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Second Name", "Id", "Subscription_End_Date", "Coach Id"
            }
        ));
        jScrollPane3.setViewportView(Table_List);

        Refresh_DB.setBackground(new java.awt.Color(62, 114, 236));
        Refresh_DB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Refresh_DB.setForeground(new java.awt.Color(255, 255, 255));
        Refresh_DB.setText("Refresh");
        Refresh_DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_DBActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(62, 114, 236));
        jLabel18.setText("Members List");

        javax.swing.GroupLayout List_Member_page_panelLayout = new javax.swing.GroupLayout(List_Member_page_panel);
        List_Member_page_panel.setLayout(List_Member_page_panelLayout);
        List_Member_page_panelLayout.setHorizontalGroup(
            List_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, List_Member_page_panelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Refresh_DB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, List_Member_page_panelLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        List_Member_page_panelLayout.setVerticalGroup(
            List_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, List_Member_page_panelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(List_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(List_Member_page_panelLayout.createSequentialGroup()
                        .addComponent(Refresh_DB, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(List_Member_page_panelLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addGap(29, 29, 29)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("tab3", List_Member_page_panel);

        Update_Member_page_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("ID");

        Update_id_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_id_searchActionPerformed(evt);
            }
        });

        Update_pass_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_pass_newActionPerformed(evt);
            }
        });

        Update_sun_end_date_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_sun_end_date_newActionPerformed(evt);
            }
        });

        Update_coach_id_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_coach_id_newActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("New Password");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("New sub_End-Date");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("New Coach");

        Update_new_update.setBackground(new java.awt.Color(62, 114, 236));
        Update_new_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update_new_update.setForeground(new java.awt.Color(255, 255, 255));
        Update_new_update.setText("Update");
        Update_new_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_new_updateActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(62, 114, 236));
        jLabel25.setText("Update Member");

        javax.swing.GroupLayout Update_Member_page_panelLayout = new javax.swing.GroupLayout(Update_Member_page_panel);
        Update_Member_page_panel.setLayout(Update_Member_page_panelLayout);
        Update_Member_page_panelLayout.setHorizontalGroup(
            Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update_Member_page_panelLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Update_id_search, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(245, 245, 245))
            .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Update_sun_end_date_new, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(Update_coach_id_new))
                            .addComponent(Update_pass_new, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(Update_new_update, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Update_Member_page_panelLayout.setVerticalGroup(
            Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                        .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Update_id_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(Update_pass_new, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Update_sun_end_date_new, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Update_coach_id_new, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(Update_new_update, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jTabbedPane1.addTab("tab4", Update_Member_page_panel);

        Report_Member_page_panel.setBackground(new java.awt.Color(255, 255, 255));

        send_report.setBackground(new java.awt.Color(62, 114, 236));
        send_report.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        send_report.setForeground(new java.awt.Color(255, 255, 255));
        send_report.setText("Send");
        send_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_reportActionPerformed(evt);
            }
        });

        admin_id_report_sender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_id_report_senderActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Admin ID");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Member ID");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Report Message");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(62, 114, 236));
        jLabel26.setText("Send a Report");

        javax.swing.GroupLayout Report_Member_page_panelLayout = new javax.swing.GroupLayout(Report_Member_page_panel);
        Report_Member_page_panel.setLayout(Report_Member_page_panelLayout);
        Report_Member_page_panelLayout.setHorizontalGroup(
            Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Report_Member_page_panelLayout.createSequentialGroup()
                .addGroup(Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Report_Member_page_panelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Report_Member_page_panelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))))
                .addGap(18, 18, 18)
                .addGroup(Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(member_id_report_reciever, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin_id_report_sender, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(report_text, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Report_Member_page_panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(send_report, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        Report_Member_page_panelLayout.setVerticalGroup(
            Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Report_Member_page_panelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(admin_id_report_sender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(member_id_report_reciever, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(report_text, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(send_report, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        jTabbedPane1.addTab("tab6", Report_Member_page_panel);

        Add_Member_page_panel.setBackground(new java.awt.Color(255, 255, 255));

        Member_FirstName_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Member_FirstName_AddActionPerformed(evt);
            }
        });

        Member_LastName_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Member_LastName_AddActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Last Name :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("First Name :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Email :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Password :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Membership :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Coach ID :");

        Submit_Add.setBackground(new java.awt.Color(62, 114, 236));
        Submit_Add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Submit_Add.setForeground(new java.awt.Color(255, 255, 255));
        Submit_Add.setText("Submit");
        Submit_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_AddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID :");

        Member_id_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Member_id_addActionPerformed(evt);
            }
        });

        Member_Email_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Member_Email_AddActionPerformed(evt);
            }
        });

        Member_pass_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Member_pass_addActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Age :");

        Member_sub_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Member_sub_startActionPerformed(evt);
            }
        });

        Member_sub_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Member_sub_endActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Subscription Start Date :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Subscription Start End :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 114, 236));
        jLabel2.setText("Add a Member :");

        jLabel22.setForeground(new java.awt.Color(62, 114, 236));
        jLabel22.setText("_____________________________________________________");

        javax.swing.GroupLayout Add_Member_page_panelLayout = new javax.swing.GroupLayout(Add_Member_page_panel);
        Add_Member_page_panel.setLayout(Add_Member_page_panelLayout);
        Add_Member_page_panelLayout.setHorizontalGroup(
            Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                        .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Member_id_add, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Member_FirstName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Member_LastName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Member_Email_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Member_pass_add, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Member_membership_add, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Member_coachid_add, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Member_page_panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Member_age_add, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                        .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Member_sub_start, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Member_sub_end, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Submit_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        Add_Member_page_panelLayout.setVerticalGroup(
            Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(16, 16, 16)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Member_id_add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Member_FirstName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Member_LastName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Member_Email_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Member_pass_add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(Member_membership_add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Member_coachid_add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(Member_age_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Member_sub_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Member_sub_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(Submit_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", Add_Member_page_panel);

        Delete_Member_page_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Wanted ID");

        delet_member.setBackground(new java.awt.Color(62, 114, 236));
        delet_member.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delet_member.setForeground(new java.awt.Color(255, 255, 255));
        delet_member.setText("Delete");
        delet_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delet_memberActionPerformed(evt);
            }
        });

        Refresh_Delet_member.setBackground(new java.awt.Color(62, 114, 236));
        Refresh_Delet_member.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Refresh_Delet_member.setForeground(new java.awt.Color(242, 242, 242));
        Refresh_Delet_member.setText("Refresh");
        Refresh_Delet_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_Delet_memberActionPerformed(evt);
            }
        });

        Table_List1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Second Name", "Id", "Subscription_End_Date", "Coach Id"
            }
        ));
        jScrollPane5.setViewportView(Table_List1);

        javax.swing.GroupLayout Delete_Member_page_panelLayout = new javax.swing.GroupLayout(Delete_Member_page_panel);
        Delete_Member_page_panel.setLayout(Delete_Member_page_panelLayout);
        Delete_Member_page_panelLayout.setHorizontalGroup(
            Delete_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Delete_Member_page_panelLayout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(Delete_Member_page_panelLayout.createSequentialGroup()
                .addGroup(Delete_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Delete_Member_page_panelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(member_id_delet, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(Refresh_Delet_member, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Delete_Member_page_panelLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(delet_member, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Delete_Member_page_panelLayout.setVerticalGroup(
            Delete_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_Member_page_panelLayout.createSequentialGroup()
                .addGroup(Delete_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Delete_Member_page_panelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Refresh_Delet_member, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Delete_Member_page_panelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(Delete_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(member_id_delet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delet_member, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("tab5", Delete_Member_page_panel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -39, 730, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Back_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_Member_page_btnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == Back_Member_page_btn){
            try{
 
             value_back = stk.peek();
            }catch(EmptyStackException  ex){
                System.out.println(ex);
            }
           try{
               
               value_back = stk.pop();
              
           }catch(Exception e){
            System.out.println(e);
            
        }finally{
         jTabbedPane1.setSelectedIndex(value_back);
  
           }
           
       
        }
    }//GEN-LAST:event_Back_Member_page_btnActionPerformed

   
    private void Delet_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delet_Member_page_btnActionPerformed
        if(evt.getSource() == Delet_Member_page_btn){
            jTabbedPane1.setSelectedIndex(3);
            stk.push(4);
             if(flag_delet == true){
                show_delet_table();
                flag_delet = false;
                }
          
        }
                     

    }//GEN-LAST:event_Delet_Member_page_btnActionPerformed

    private void List_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_List_Member_page_btnActionPerformed
         if(evt.getSource() == List_Member_page_btn){
                jTabbedPane1.setSelectedIndex(1);
                stk.push(2);
                if(flag_list == true){
                ShowData();
                flag_list = false;
                }
                
        }
    }//GEN-LAST:event_List_Member_page_btnActionPerformed

    private void Add_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Member_page_btnActionPerformed
        if(evt.getSource() == Add_Member_page_btn){
        jTabbedPane1.setSelectedIndex(5);
        stk.push(0);
        // create connection
       
          
          
            
            
        
        }
    }//GEN-LAST:event_Add_Member_page_btnActionPerformed

    private void Search_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Member_page_btnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == Search_Member_page_btn){
                jTabbedPane1.setSelectedIndex(0);
                stk.push(1);
        }

    }//GEN-LAST:event_Search_Member_page_btnActionPerformed

    private void Update_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Member_page_btnActionPerformed
         if(evt.getSource() == Update_Member_page_btn){
                jTabbedPane1.setSelectedIndex(2);
                stk.push(3);
        }

    }//GEN-LAST:event_Update_Member_page_btnActionPerformed

    private void Report_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Report_Member_page_btnActionPerformed
        // TODO add your handling code here:
         if(evt.getSource() == Report_Member_page_btn){
             stk.push(5);
                jTabbedPane1.setSelectedIndex(4);
                
        }
                    

    }//GEN-LAST:event_Report_Member_page_btnActionPerformed

    private void Update_coach_id_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_coach_id_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_coach_id_newActionPerformed

    private void Update_new_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_new_updateActionPerformed
try{
     c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
     if(Update_id_search.getText().equalsIgnoreCase("")){
         JOptionPane.showMessageDialog(this, "No Input Id");
         
     }
     else{

        int input_id = Integer.parseInt(Update_id_search.getText());

        String query;
        java.sql.Statement ss = c.createStatement();
        
        if(!Update_pass_new.getText().equals("")){
           query =  "update member set  member_password = ' " +Update_pass_new.getText()+" '  where member_id = ' " +input_id+" ' ";
            ss.execute(query);
        }
        if(!Update_sun_end_date_new.getText().equals("")){
          query = " update member set member_subscription_endDate = ' " +Date.valueOf(Update_sun_end_date_new.getText())+" '  where member_id =' " +input_id+ " ' ";
          ss.execute(query);
        }
        if(!Update_coach_id_new.getText().equals("")){
            query = "select count(coach_id) as cnt from coach  where coach_id = ' " +Integer.parseInt(Update_coach_id_new.getText())+" ' ";
         p1 =c.prepareStatement(query);
        ResultSet rr = p1.executeQuery();
                 rr.next();
                 if(rr.getInt("cnt") <= 0){
                     JOptionPane.showMessageDialog(this, "invalid coach id");
                     return;
        }
                   
        }
     }
    
}catch(SQLException ex){
    System.out.println(ex);
}
        
    }//GEN-LAST:event_Update_new_updateActionPerformed

    private void Update_pass_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_pass_newActionPerformed
           
    }//GEN-LAST:event_Update_pass_newActionPerformed

            @SuppressWarnings("empty-statement")
    private void send_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_reportActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == send_report){
            boolean popup = true;
            try {
                c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
             String content = report_text.getText();
                String sender = admin_id_report_sender.getText();
                String receiver = member_id_report_reciever.getText();
                int senderId = Integer.parseInt(sender);
                System.out.println(senderId);
            String check = "select count(admin_id) as cnt from admin  where admin_id = ' " +senderId+" ' ";
           PreparedStatement p =c.prepareStatement(check);
              ResultSet rr = p.executeQuery();
              rr.next();
               // System.out.println(rr.getInt("cnt"));
                if(rr.getInt("cnt") > 0){
                  
                int recieverid = Integer.parseInt(receiver);
                Date current  = Date.valueOf( java.time.LocalDate.now());
                String query = " insert into  report values(' "+content+" ',' "+current+" ',' "+senderId+" ',' "+recieverid+" ' ) ";
                java.sql.Statement ss = c.createStatement();
                ss.execute(query);
                  JOptionPane.showMessageDialog(this,"Sent Successfully");
               }
                else{
                    JOptionPane.showMessageDialog(this,"Fail\n maybe invalid data");
                }
                
                 
               
            } catch (SQLException ex) {
                Logger.getLogger(Member_page.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(this,"Fail\n maybe invalid data");
                
            }
          
           

        }
    }//GEN-LAST:event_send_reportActionPerformed

    private void Refresh_DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_DBActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m = (DefaultTableModel) Table_List.getModel();
        m.setRowCount(0);
         
        ShowData();
    }//GEN-LAST:event_Refresh_DBActionPerformed

    private void Refresh_Delet_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_Delet_memberActionPerformed
      
      DefaultTableModel t1 = (DefaultTableModel) Table_List1.getModel();
          t1.setRowCount(0);
          show_delet_table();
    }//GEN-LAST:event_Refresh_Delet_memberActionPerformed

    private void delet_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delet_memberActionPerformed
         try {
                c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
             String content = report_text.getText();
        String Member_Id_delet = member_id_delet.getText();
        int member_delet = Integer.parseInt(Member_Id_delet);
        String query = "delete from member where member_id = ' "+member_delet+" ' ";
        
         String check1 = "select count(member_id) as cnt from member  where member_id = ' " +member_delet+" ' ";
            p1 =c.prepareStatement(check1);
              ResultSet rr1 = p1.executeQuery();
              rr1.next();
               // System.out.println(rr.getInt("cnt"));
                if(rr1.getInt("cnt") > 0){
                 java.sql.Statement ss = c.createStatement();
                ss.execute(query);
                JOptionPane.showMessageDialog(this,"Successfully Deleted");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Failed Deleted");
                }
        
         
         }
        catch(Exception ex){
                System.out.println(ex);
                    JOptionPane.showMessageDialog(this,"Invalid Data");
                }
         
    }//GEN-LAST:event_delet_memberActionPerformed

    private void admin_id_report_senderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_id_report_senderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_id_report_senderActionPerformed

    private void Update_sun_end_date_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_sun_end_date_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_sun_end_date_newActionPerformed

    private void Search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == Search_btn){
            
         if(id_search_field.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Invalid Input");
             return;
         }
         else{
             
             try {
                 int id_search = Integer.parseInt(id_search_field.getText());
                  c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
                 String check1 = "select count(member_id) as cnt from member  where member_id = ' " +id_search+" ' ";
                 p1 =c.prepareStatement(check1);
                 ResultSet rr1 = p1.executeQuery();
                 rr1.next();
                 System.out.println(rr1.getInt("cnt"));
                 // System.out.println(rr.getInt("cnt"));
                  DefaultTableModel m = (DefaultTableModel) Search_Table.getModel();
                   m.setRowCount(0);
                 if(rr1.getInt("cnt") > 0){
                     p = c.prepareStatement("select * from member where member_id = ' " +id_search+" ' ");
                     ResultSet r = p.executeQuery();
                     ArrayList<Member>search_data = new ArrayList<>();
                     
                      Object[ ]row = new Object[5];
                       Member m1;
                      while(r.next()){
                    m1 = new Member(r.getString("member_firstName"),r.getString("member_lastName"),r.getInt("member_id"),r.getDate("member_subscription_endDate"),r.getInt("member_coachId"));
                    search_data.add(m1);
                      }            
                     
                                  row[0] = search_data.get(0).getFirstName();
                                  row[1] =  search_data.get(0).getLastName();
                                  row[2] =  search_data.get(0).getId();
                                  row[3] =  search_data.get(0).getDateSubscriptionEnd();
                                  row[4] =  search_data.get(0).getCoachId();
                                      m.addRow(row);

                   
                 }
                
                 
                 
                 else{
                       JOptionPane.showMessageDialog(this, "Fail");
                 }
             } catch (SQLException ex) {
                 Logger.getLogger(Member_page.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        }
    }//GEN-LAST:event_Search_btnActionPerformed

    private void logout_member_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_member_adminActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == logout_member_admin){
            login main_logout = new login();
            main_logout.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logout_member_adminActionPerformed

    private void Update_id_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_id_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_id_searchActionPerformed

    private void Member_sub_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Member_sub_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Member_sub_endActionPerformed

    private void Member_pass_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Member_pass_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Member_pass_addActionPerformed

    private void Member_Email_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Member_Email_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Member_Email_AddActionPerformed

    private void Member_id_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Member_id_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Member_id_addActionPerformed

    private void Submit_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_AddActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == Submit_Add){
           

            // create statement
            boolean check = false;
            try {
                 c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");

//                String Fname = Member_FirstName_Add.getText();
//                String Sname = Member_LastName_Add.getText();
//                String Email = Member_Email_Add.getText();
//                int  membership = Integer.parseInt(Member_membership_add.getText());
//                int coachid =Integer.parseInt(Member_coachid_add.getText());
//                String pass =Member_pass_add.getText();
//                int id =Integer.parseInt( Member_id_add.getText());
//                int age  = Integer.parseInt(Member_age_add.getText());
//                Date startDate =  Date.valueOf(   Member_sub_start.getText() );
//                Date endDate =Date.valueOf(Member_sub_end.getText());
                if(Member_FirstName_Add.getText().isEmpty()|| Member_LastName_Add.getText().isEmpty()||Member_Email_Add.getText().isEmpty()
                        ||Member_membership_add.getText().isEmpty()||Member_coachid_add.getText().isEmpty()|| Member_pass_add.getText().isEmpty()
                        ||Member_id_add.getText().isEmpty() || Member_age_add.getText().isEmpty() || Member_sub_start.getText().isEmpty() 
                        ||  Member_sub_end.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Missed input field");
                    
             
                }
                else{
                
                 String query = "select count(coach_id) as cnt from coach  where coach_id = ' " +Integer.parseInt(Member_coachid_add.getText())+" ' ";
         p1 =c.prepareStatement(query);
        ResultSet rr = p1.executeQuery();
                 rr.next();
                 if(rr.getInt("cnt") <= 0){
                     JOptionPane.showMessageDialog(this, "invalid coach id");
                     return;
               }
                
                java.sql.Statement  ss;
                ss = c.createStatement();
                //create query
                //missed coach_id
                 query = "insert into member (member_id,member_firstName,member_lastName,member_subscription,member_email,member_password,member_age,member_subscription_startDate ,member_subscription_endDate ,member_coachId)values(' "+Integer.parseInt( Member_id_add.getText())+" ' ,' " +Member_FirstName_Add.getText()+" ' ,' " + Member_LastName_Add.getText()+ " ',  ' " +Member_pass_add.getText()+ " ',' " +Member_Email_Add.getText()+ " ',' " +Member_pass_add.getText()+ " ' ,' " +Integer.parseInt(Member_age_add.getText())+ " '  ,' " +Date.valueOf(   Member_sub_start.getText() )+" '  ,' "+Date.valueOf(Member_sub_end.getText())+" ',' "+Integer.parseInt(Member_coachid_add.getText()) + " ')";
                ss.execute( query);
                JOptionPane.showMessageDialog(this,"Member Added Successfully");
                ClearFields();
                }
            } catch (Exception ex) {
                Logger.getLogger(Member_page.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,"Fail");
                check = true;
            }
           
                
            

        }
        // endof the method
    }//GEN-LAST:event_Submit_AddActionPerformed

    private void Member_LastName_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Member_LastName_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Member_LastName_AddActionPerformed

    private void Member_FirstName_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Member_FirstName_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Member_FirstName_AddActionPerformed

    private void Member_sub_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Member_sub_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Member_sub_startActionPerformed
// clear all add fields
    private void ClearFields(){
    Member_Email_Add.setText("");
    Member_FirstName_Add.setText("");
    Member_LastName_Add.setText("");
    Member_age_add.setText("");
    Member_coachid_add.setText("");
    Member_id_add.setText("");
    Member_membership_add.setText("");
        Member_pass_add.setText("");
        Member_sub_end.setText("");
        Member_sub_start.setText("");
}
    
    private  void ShowData(){
 ArrayList<Member>Data_Table = new ArrayList<>();
      

 try{
           c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
        p = c.prepareStatement("select * from member");
        ResultSet r = p.executeQuery();
        DefaultTableModel m = (DefaultTableModel) Table_List.getModel();
                DefaultTableModel t1 = (DefaultTableModel) Table_List1.getModel();

           Object[ ]row = new Object[5];
        while(r.next()){
            
//Member_DataBase_Version m1 = new Member_DataBase_Version(r.getString("member_firstName"),r.getString("member_lastName"),r.getInt("member_id"),r.getString("member_subscription_endDate "),r.getInt("member_coachId"));
Member m1 = new Member(r.getString("member_firstName"),r.getString("member_lastName"),r.getInt("member_id"),r.getDate("member_subscription_endDate"),r.getInt("member_coachId"));
            Data_Table.add(m1);
            
        }
        for(int i=0;i<Data_Table.size();i++){
          row[0] = Data_Table.get(i).getFirstName();
      row[1] =  Data_Table.get(i).getLastName();
         row[2] =  Data_Table.get(i).getId();
         row[3] =  Data_Table.get(i).getDateSubscriptionEnd();
      row[4] =  Data_Table.get(i).getCoachId();
     

         m.addRow(row);
         

        }
       // ShowData();
        
        
       
 }catch(SQLException ex){
     System.out.println(ex);
     try {
         c.close();
     } catch (SQLException ex1) {
         Logger.getLogger(Member_page.class.getName()).log(Level.SEVERE, null, ex1);
     }
 }
 }
    private void  show_delet_table(){
         ArrayList<Member>Data_Table = new ArrayList<>();
      

 try{
           c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
        p = c.prepareStatement("select * from member");
        ResultSet r = p.executeQuery();
        
                DefaultTableModel t1 = (DefaultTableModel) Table_List1.getModel();

           Object[ ]row = new Object[5];
        while(r.next()){
            
//Member_DataBase_Version m1 = new Member_DataBase_Version(r.getString("member_firstName"),r.getString("member_lastName"),r.getInt("member_id"),r.getString("member_subscription_endDate "),r.getInt("member_coachId"));
Member m1 = new Member(r.getString("member_firstName"),r.getString("member_lastName"),r.getInt("member_id"),r.getDate("member_subscription_endDate"),r.getInt("member_coachId"));
            Data_Table.add(m1);
            
        }
        for(int i=0;i<Data_Table.size();i++){
          row[0] = Data_Table.get(i).getFirstName();
      row[1] =  Data_Table.get(i).getLastName();
         row[2] =  Data_Table.get(i).getId();
         row[3] =  Data_Table.get(i).getDateSubscriptionEnd();
      row[4] =  Data_Table.get(i).getCoachId();
     

       
         t1.addRow(row);

        }
       // ShowData();
        
        
       
 }catch(SQLException ex){
     System.out.println(ex);
     try {
         c.close();
     } catch (SQLException ex1) {
         Logger.getLogger(Member_page.class.getName()).log(Level.SEVERE, null, ex1);
     }
 }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member_page().setVisible(true);
               
              // ShowData();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Member_page_btn;
    private javax.swing.JPanel Add_Member_page_panel;
    private javax.swing.JButton Back_Member_page_btn;
    private javax.swing.JButton Delet_Member_page_btn;
    private javax.swing.JPanel Delete_Member_page_panel;
    private javax.swing.JButton List_Member_page_btn;
    private javax.swing.JPanel List_Member_page_panel;
    private javax.swing.JTextField Member_Email_Add;
    private javax.swing.JTextField Member_FirstName_Add;
    private javax.swing.JTextField Member_LastName_Add;
    private javax.swing.JTextField Member_age_add;
    private javax.swing.JTextField Member_coachid_add;
    private javax.swing.JTextField Member_id_add;
    private javax.swing.JTextField Member_membership_add;
    private javax.swing.JTextField Member_pass_add;
    private javax.swing.JTextField Member_sub_end;
    private javax.swing.JTextField Member_sub_start;
    private javax.swing.JButton Refresh_DB;
    private javax.swing.JButton Refresh_Delet_member;
    private javax.swing.JButton Report_Member_page_btn;
    private javax.swing.JPanel Report_Member_page_panel;
    private javax.swing.JButton Search_Member_page_btn;
    private javax.swing.JPanel Search_Member_page_panel;
    private javax.swing.JTable Search_Table;
    private javax.swing.JButton Search_btn;
    private javax.swing.JButton Submit_Add;
    private javax.swing.JTable Table_List;
    private javax.swing.JTable Table_List1;
    private javax.swing.JButton Update_Member_page_btn;
    private javax.swing.JPanel Update_Member_page_panel;
    private javax.swing.JTextField Update_coach_id_new;
    private javax.swing.JTextField Update_id_search;
    private javax.swing.JButton Update_new_update;
    private javax.swing.JTextField Update_pass_new;
    private javax.swing.JTextField Update_sun_end_date_new;
    private javax.swing.JTextField admin_id_report_sender;
    private javax.swing.JButton delet_member;
    private javax.swing.JTextField id_search_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logout_member_admin;
    private javax.swing.JTextField member_id_delet;
    private javax.swing.JTextField member_id_report_reciever;
    private javax.swing.JTextField report_text;
    private javax.swing.JButton send_report;
    // End of variables declaration//GEN-END:variables
}
